name: terraform_plan

on:
  workflow_call:
    inputs:
      terraform_version:
        description: 'Terraform version to use'
        required: true
        default: '1.12'
        type: string
      working_directory:
        description: 'Directory containing Terraform configuration files'
        required: true
        default: '.'
        type: string
      

jobs:
  determine_provider:
    uses: ./.github/workflows/_determine_provider.yaml
    secrets: inherit
  terraform:
    name: 'Terraform Plan'
    runs-on: ubuntu-latest
    needs: determine_provider
    permissions:
      contents: read
      pull-requests: write
    outputs:
      plan_file: ${{ steps.plan.outputs.plan_file }}
    defaults:
      run:
        shell: bash
        working-directory: ${{ inputs.working_directory }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3.1.2
      with:
        terraform_version: ${{ inputs.terraform_version }}

    - name: Authenticate Azure
      if: needs.determine_provider.outputs.azure == 'true'
      uses: azure/login@v2
      with:
        client-id: ${{ secrets.ARM_CLIENT_ID }}
        tenant-id: ${{ secrets.ARM_TENANT_ID }}
        subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        enable-AzPsession: true

    - name: Terraform Init Azure
      if: needs.determine_provider.outputs.azure == 'true'
      env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_USE_OIDC: true
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      run: |
        terraform init \
        -backend-config="storage_account_name=${{ secrets.AZ_STATE_STORE }}" \
        -backend-config="container_name=${{ secrets.AZ_STATE_CONTAINER }}" \
        -backend-config="key=terraform.tfstate" \

#    - name: Terraform Init AWS
#      if: needs.determine_provider.outputs.aws == 'true'
#      env:
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#      run: |
#        terraform init \
#        -backend-config="bucket=${{ secrets.AWS_STATE_BUCKET }}" \
#        -backend-config="key=terraform.tfstate" \
#        -backend-config="region=${{ secrets.AWS_STATE_REGION }}" \
#        -backend-config="access_key=${{ secrets.AWS_ACCESS_KEY }}" \
#

    - name: Authenticate GCP
      if: needs.determine_provider.outputs.gcp == 'true'
      uses: google-github-actions/auth@v2.1.12
      with:
        workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
        service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
        create_credentials_file: true
        token_format: "access_token"

    - name: Terraform Init GCP
      if: needs.determine_provider.outputs.gcp == 'true'
      run: |
        terraform init \
        -backend-config="bucket=${{ secrets.GOOGLE_STATE_BUCKET }}" \
        -backend-config="prefix=terraform/state" 


    ## we run the same plan command for all providers to get the plan output
    #TODO add plan output as a comment in pull request
    - name: Terraform Plan
      id: plan
      run: |
        terraform plan -input=false \
        -out=tfplan && \
        echo "Terraform plan created successfully." && \
        cat tfplan && \
        echo "::setOutput name=plan_file::$(cat tfplan)"
